"""Distil sagittal joint cages from the official MHR v1.0.1 TorchScript asset.

Requires numpy/torch, and build/research/mhr_model.pt from the release assets.zip.
Tracks barycentric points on a neutral midsagittal surface section, rather than
fitting circles or using a convex hull (which would fill the flexion crease).
The app ships only the small sampled cages, not the model or a Python runtime.
"""
from pathlib import Path
import argparse
import numpy as np
import torch

parser = argparse.ArgumentParser()
parser.add_argument('--model', default='build/research/mhr_model.pt')
parser.add_argument('--output', default='src/main/resources/skinning/mhr-joints.tsv')
args = parser.parse_args()
model = torch.jit.load(args.model, map_location='cpu').eval()
buffers = dict(model.named_buffers())
faces = buffers['character_torch.mesh.faces'].numpy()
parents = buffers['character_torch.skeleton.joint_parents'].numpy()
assert faces.shape == (36874,3), 'Expected MHR v1.0.1 LOD1 topology'
transform = buffers['character_torch.parameter_transform.parameter_transform'].numpy()
for joint, parameter in [(3,62),(40,36)]:
    assert transform[joint*7+5,parameter] == 1, 'Unexpected knee/elbow parameter mapping'

def pose(parameter, value):
    parameters = torch.zeros(1, 204)
    parameters[0, parameter] = value
    with torch.no_grad():
        vertices, joints = model(torch.zeros(1, 45), parameters, torch.zeros(1, 72), True)
    return vertices[0].numpy(), joints[0].numpy()

def rotate(q, v):
    return v + 2 * np.cross(q[:3], np.cross(q[:3], v) + q[3] * v)

_, neutral = pose(0, 0)
rows = []
for kind, joint, distal, parameter, limb in [('knee', 3, 4, 62, range(2,18)), ('elbow',40,41,36,range(39,74))]:
    axis = rotate(neutral[joint,3:7], np.array([0.,0.,1.]))
    u = neutral[joint,:3] - neutral[parents[joint],:3]
    u -= axis * np.dot(u,axis)
    u /= np.linalg.norm(u)
    n = np.cross(axis,u)
    d = neutral[distal,:3] - neutral[joint,:3]
    straight = -float(np.arctan2(d@n,d@u))
    rest, state = pose(parameter, straight)
    origin = state[joint,:3]
    local = rest - origin
    mass = np.zeros(len(rest))
    skin_bones = buffers['character_torch.linear_blend_skinning.skin_indices_flattened'].numpy()
    skin_vertices = buffers['character_torch.linear_blend_skinning.vert_indices_flattened'].numpy()
    skin_weights = buffers['character_torch.linear_blend_skinning.skin_weights_flattened'].numpy()
    selected = np.isin(skin_bones,list(limb))
    np.add.at(mass,skin_vertices[selected],skin_weights[selected])
    segments = []
    for tri in faces[np.mean(mass[faces],axis=1) > .5]:
        lateral = local[tri]@axis
        cuts = []
        for a,c in [(0,1),(1,2),(2,0)]:
            if lateral[a]*lateral[c] >= 0: continue
            t = lateral[a]/(lateral[a]-lateral[c])
            w = np.zeros(3); w[a]=1-t;w[c]=t
            p = w@local[tri]
            cuts.append((np.array([p@u,p@n]),w))
        if len(cuts)==2: segments.append((tri,cuts))

    def section(s):
        hits=[]
        for tri, ((a,wa),(c,wc)) in segments:
            if (a[0]-s)*(c[0]-s)>0 or abs(c[0]-a[0])<1e-9: continue
            t=(s-a[0])/(c[0]-a[0])
            hits.append((float(a[1]+t*(c[1]-a[1])),tri,wa+t*(wc-wa)))
        if len(hits)<2: raise ValueError(f'No closed {kind} section at {s}')
        return min(hits,key=lambda h:h[0]),max(hits,key=lambda h:h[0])

    low,high=section(0)
    radius=(high[0]-low[0])/2
    samples=[(s,section(s*radius)) for s in np.linspace(-3,3,25)]
    print(kind,'radius cm',radius,'straight offset degrees',np.degrees(straight))
    for angle in [0,15,30,45,60,75,90,105,120,135,150]:
        vertices,_=pose(parameter,straight+np.radians(angle))
        for s,(low,high) in samples:
            coords=[]
            for _,tri,w in [low,high]:
                p=w@(vertices[tri]-origin)
                coords += [float(p@u/radius),float(p@n/radius)]
            rows.append([kind,str(angle),f'{s:.6f}',f'{low[0]/radius:.6f}',f'{high[0]/radius:.6f}',*[f'{x:.6f}' for x in coords]])
output=Path(args.output);output.parent.mkdir(parents=True,exist_ok=True)
output.write_text('# MHR v1.0.1, Apache-2.0; generated by tools/research/extract_mhr_joint_templates.py\n'
                  '# kind angle axial rest_low rest_high posed_low_axial posed_low_normal posed_high_axial posed_high_normal\n'
                  +'\n'.join('\t'.join(r) for r in rows)+'\n',encoding='utf8')
